package com.example.engine

data class TelemetryState(
  val fps: Float = 60.0f,
  val drawCalls: Int = 14,
  val vertexCount: Int = 2400,
  val triangleCount: Int = 1200,
  val ramUsageMb: Long = 64L,
  val isGpuAccelerated: Boolean = true,
  val rendererEngine: String = "Google Filament gltfio (PBR)",
  val spatialTrackingEngine: String = "Google ARCore 6DoF",
  val arTrackingStatus: String = "TRACKING",
  val horizontalPlanesCount: Int = 0,
  val verticalPlanesCount: Int = 0,
  val trackedImagesCount: Int = 0,
  val activeAnchorsCount: Int = 0,
  val walkingDisplacementMeters: Float = 0f,
  val lightIntensityLumens: Float = 1000.0f,
  val isDepthEnabled: Boolean = true,
  val depthMinMeters: Float = 0.3f,
  val depthMaxMeters: Float = 4.5f,
  val depthAvgMeters: Float = 1.8f,
  val depthOcclusionDetected: Boolean = false,
  val occlusionPercentage: Float = 0f,
  val isGpuDepthOcclusionActive: Boolean = false,
  val isDepthTextureBoundToPipeline: Boolean = false,
  val isDepthConfidenceAvailable: Boolean = false,
  val depthConfidencePercentage: Float? = null,
  val depthCoveragePercentage: Float = 0f,
  val metricDimensions: String = "1.00m x 0.85m x 1.10m (1:1 Scale)",
  val currentAnimationTrack: Int = 0,
  val totalAnimationTracks: Int = 1,
  val thermalStatus: String = "Nominal (Safe)",
  val isInstantPlacementActive: Boolean = true,
  val isGeospatialActive: Boolean = false,
  val earthTrackingState: String = "IDLE",
  val earthCoordinates: String = "0.000000°, 0.000000°",
  val vpsAvailability: String = "UNAVAILABLE",
  val cloudAnchorsCount: Int = 0,
  val isRealtimeBackendConnected: Boolean = false,
  val isMultiplayerActive: Boolean = false,
  val dominantSemanticLabel: String = "SCANNING",
  val isGpuSemanticRenderingActive: Boolean = false,
  val depthConfidenceScore: Float = 95f,
  val deviceTier: String = "TIER_A_FLAGSHIP",
  val isGoogleCertifiedDevice: Boolean = false,
  val isArCoreSupported: Boolean = true,
  val isArCoreInstalled: Boolean = true,
  val mrPassthroughSemantics: String = "Monoscopic Passthrough + Stereoscopic Virtual Rendering",
  val isTrueBinocularPassthrough: Boolean = false,
  val arRecordingStatus: String = "STOPPED",
  val environmentalMeshTriangles: Int = 0,
  val environmentalMeshAreaSqM: Float = 0f,
  val hasReal3dMeshGeometry: Boolean = false,
  val streetscapeGeometriesCount: Int = 0,
  val denseMeshChunksCount: Int = 0,
  val isDenseLocalMeshActive: Boolean = false,
  val isFull3dSceneReconstruction: Boolean = false,
  val logs: List<LogEntry> = emptyList()
)

data class LogEntry(
  val timestamp: Long = System.currentTimeMillis(),
  val level: String = "INFO",
  val tag: String,
  val message: String
)
